#ifndef DEVICE_CONFIGURATION_H
#define DEVICE_CONFIGURATION_H

#include "driver/gpio.h"

#define I2C_MASTER_SCL_IO_1 GPIO_NUM_14
#define I2C_MASTER_SDA_IO_1 GPIO_NUM_15
#define I2C_MASTER_SCL_IO_2 GPIO_NUM_7
#define I2C_MASTER_SDA_IO_2 GPIO_NUM_6

#define BUTTON_GPIO GPIO_NUM_0
#define BUTTON_PIN_BITMASK (1ULL << BUTTON_GPIO)
#define PRESS_DURATION_TO_SLEEP_MS 6000
#define PRESS_DURATION_TO_CONFIGURATION_MS 3000

#define LP5036_ADDRESS_1 0x31   // u14
#define LP5036_ADDRESS_2 0x30   // u6
#define LP5036_ADDRESS_3 0x32 //u13

#define TOTAL_REGION_COUNT 6  //TODO: Değiştir.
#define MAX_NUM_OF_LED_OF_LP5036 36
#define NUM_OF_LASER_DRIVERS 3

#define MAX_FRAGMENT_SIZE 244
#define MIN_FRAGMENT_SIZE 12
#define MAX_FRAGMENT_COUNT 100
#define DEFAULT_FRAGMENT_SIZE 30

#define LASER_DRIVER_ENABLE_GPIO GPIO_NUM_17
#define LED_DRIVER_ENABLE_GPIO GPIO_NUM_1
#define MODE_INDICATOR_LED_GPIO GPIO_NUM_8

#define MAX_PENDING_MESSAGES 100
#define MAX_MESSAGE_DATA_SIZE 500
#define MAX_TIMEOUT_DURATION 20000
#define DYNAMIC_PERIOD 500
#define MAX_MESSAGE_RETRY_COUNT 2
#define RETRY_DELAY_DURATION 100
#define MAX_STATE_LISTENERS 5

#define MAX_NUM_OF_SENSORS 2
#define NORMAL_PIN_STATUS 1  // Default hali HIGH //TODO: (sensörün INT bacağı active-low ise NORMAL=1 doğru; değilse tersle).

#define FIRST_PROX_SENSOR_INT_GPIO GPIO_NUM_18
#define SECOND_PROX_SENSOR_INT_GPIO GPIO_NUM_4
#define VCNL_3020_ADDRESS  0x13

#define PROXIMITY_LOWER_THRESHOLD 1792
#define PROXIMITY_MAX_LOWER_THRESHOLD 2304
#define PROXIMITY_HIGHER_THRESHOLD 2688

#define MAX_RECORDS_TO_BE_SENT 20

#define FIRST_ALERT_GPIO GPIO_NUM_3
#define SECOND_ALERT_GPIO GPIO_NUM_2
#define THIRD_ALERT_GPIO GPIO_NUM_5

#define TEMPERATURE_DIFF_OFFSET 1

#define MAX_THERAPY_COUNT 16384


#define INACTIVITY_THRESHOLD_SECONDS 1200
#define ALERT_THRESHOLD_SECONDS 120
#define DEFAULT_THERAPY_DURATION 1200 //TODO: Değiştir.

#define INFINITE_THERAPY_DURATION 3599
#define MAX_THERAPY_DURATION 3600

#endif